name: rajesh_dada_padvi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
      sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5
  json_annotation: ^4.9.0
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  flutter_easyloading: ^3.0.5
  dio: ^5.7.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  shimmer_animation: ^2.2.2
  file_picker: ^10.0.0
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.3
  connectivity_plus: ^6.1.3
  network_info_plus: ^6.1.3
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  flutter_native_splash: ^2.4.6
  pdf: ^3.11.3
  printing: ^5.14.2
  mime: ^2.0.0
  intl: ^0.20.2
  firebase_messaging: ^15.2.9
  firebase_core: ^3.13.0
  flutter_local_notifications: ^19.2.1
  app_settings: ^6.1.1

  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  jwt_decoder: ^2.0.1
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/App Logos/final_app_logo.jpeg"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      # App logo
    - lib\assets\App Logos\final_app_logo.jpeg

    # certificate photo
    - lib\assets\Certificates\certificate_img.jpeg

    # Home page Icons
    - lib\assets\Icons\achievements_icon.jpeg
    - lib\assets\Icons\complaint_icon.jpeg
    - lib\assets\Icons\dummy_profile_icon.png
    - lib\assets\Icons\gallery_icon.jpeg
    - lib\assets\Icons\grievance_icon.jpeg
    - lib\assets\Icons\helpline_icon.jpeg
    - lib\assets\Icons\women_empowerment_icon.jpeg